.TH "obm-xdg" "1" "1.0" "Davide Truffa" "Openbox Pipe Menu"
.SH "NAME"
.LP 
obm\-xdg \- a pipe\-menu for openbox
.SH "SYNTAX"
.LP 
obm\-xdg [options] /path/to/system.menu
.SH "DESCRIPTION"
.LP 
\fBObm\-xdg\fR is a free desktop menus implementation for openbox.
.LP 
More information about pipe\-menus can be found on http://icculus.org/openbox/index.php/Openbox:Pipemenus
.SH "OPTIONS"
.LP 
.PP 
.IP "\fB\-\-import\fR" 10
Creates a file called "gnome\-menus.xml"
.IP "\fB\-\-replace\fR" 10
Replaces the Openbox menu with the Gnome menus

.SH "AUTHORS"
.LP 
obm\-dir  was  written by Manuel Colmenero <mkolme@gmail.com> as part of obmenu. This manual page was originally written for the Debian GNU/Linux system by Davide Truffa <davide@catoblepa.org>.
.SH "SEE ALSO"
.LP 
obmenu(1), obm\-dir(1), obm\-moz(1), obm\-nav(1), openbox(1)
