.TH "obm-nav" "1" "1.0" "Davide Truffa" "Openbox Pipe Menu"
.SH "NAME"
.LP 
obm\-nav \- a pipe\-menu for openbox
.SH "SYNTAX"
.LP 
obm\-nav <root> <filer> <terminal>
.SH "DESCRIPTION"
.LP 
\fBObm\-moz\fR is a pipe menu for openbox.
It recursively builds a menu to navigate directories.
.LP 
More information about pipe\-menus can be found on http://icculus.org/openbox/index.php/Openbox:Pipemenus
.SH "EXAMPLES"
.LP 
obm\-nav /home/bull rox xterm
.LP 

.SH "AUTHORS"
.LP 
obm\-dir  was  written by Manuel Colmenero <mkolme@gmail.com> as part of obmenu. This manual page was originally written for the Debian GNU/Linux system by Davide Truffa <davide@catoblepa.org>.
.SH "SEE ALSO"
.LP 
obmenu(1), obm\-dir(1), obm\-moz(1), obm\-xdg(1), openbox(1)
