.TH "obm-dir" "1" "1.0" "Davide Truffa" "Openbox Pipe Menu"
.SH "NAME"
.LP 
obm\-dir \- a pipe\-menu for openbox
.SH "SYNTAX"
.LP 
obm\-dir <directory> <command>
.SH "DESCRIPTION"
.LP 
\fBObm\-dir\fR is a pipe menu for openbox.
It builds a menu from a directory, alphabetically sorted and can be used inside your openbox's menu to generate menus dynamically.
.LP 
More information about pipe\-menus can be found on http://icculus.org/openbox/index.php/Openbox:Pipemenus
.SH "EXAMPLES"
.LP 
obm\-dir /home/bull/wallpaper fbsetbg
.LP 

.SH "AUTHORS"
.LP 
obm\-dir  was  written by Manuel Colmenero <mkolme@gmail.com> as part of obmenu. This manual page was originally written for the Debian GNU/Linux system by Davide Truffa <davide@catoblepa.org>.
.SH "SEE ALSO"
.LP 
obmenu(1), obm\-moz(1), obm\-nav(1), obm\-xdg(1), openbox(1)
