.TH "obm-moz" "1" "1.0" "Davide Truffa" "Openbox Pipe Menu"
.SH "NAME"
.LP 
obm\-moz \- a pipe\-menu for openbox
.SH "SYNTAX"
.LP 
obm\-moz [options]
.SH "DESCRIPTION"
.LP 
\fBObm\-moz\fR is a pipe menu for openbox.
It translates any mozilla\-compatible bookmarks into an openbox menu. 
If no arguments are given, it'll try to find your bookmarks. 
A bookmarks folder can be passed as an argument, it'll try to find it and
build the menu out of that folder.
.LP 
More information about pipe\-menus can be found on http://icculus.org/openbox/index.php/Openbox:Pipemenus
.SH "OPTIONS"
.LP 
.PP 
.IP "\fB\-h\fR, \fB\-\-help\fR" 10
Show this help message and exit
.IP "\fB\-f\fR, \fB\-\-firefox\fR" 10
Look for Firefox bookmarks
.IP "\fB\-b\fR FILENAME, \fB\-\-bookmarks\fR=FILENAME" 10
Specify the path to the bookmarks.html file
.IP "\fB\-r ROOT\fR, \fB\-\-root=ROOT\fR" 10
Root folder of the bookmarks
.IP "\fB\-n\fR BROWSER, \fB\-\-navigator=BROWSER\fR" 10
Command to run the web browser.
.SH "EXAMPLES"
.LP 
obm\-moz \-b "/path/to/bookmarks.html" \-r "Bookmarks Toolbar Folder"
.LP 

.SH "AUTHORS"
.LP 
obm\-dir  was  written by Manuel Colmenero <mkolme@gmail.com> as part of obmenu. This manual page was originally written for the Debian GNU/Linux system by Davide Truffa <davide@catoblepa.org>.
.SH "SEE ALSO"
.LP 
obmenu(1), obm\-dir(1), obm\-nav(1), obm\-xdg(1), openbox(1)
