.TH "obmenu" "1" "1.0" "Davide Truffa" "Openbox menu editor"
.SH "NAME"
.LP 
obmenu \- a menu editor for openbox
.SH "SYNTAX"
.LP 
obmenu
.SH "DESCRIPTION"
.LP 
\fBObmenu\fR is a menu editor designed for openbox.
.LP 
It\'s easy to use, allowing to get the most out of the powerful Openbox menu system, while hiding the xml layout from the user. 
It also provides a bunch of dynamic menus (pipe menus), such as Gnome menus or a quick\-navigator.
.LP 
You can also use the obxml module to easily write pipe menus of your own in Python.
.LP 
Most updated info about obmenu can be found on its home page: http://obmenu.sf.net/
.SH "AUTHORS"
.LP 
obmenu  was  written by Manuel Colmenero <mkolme@gmail.com>. This manual page was originally written for the Debian GNU/Linux system by Davide Truffa <davide@catoblepa.org>.
.SH "SEE ALSO"
.LP 
obm\-dir(1), obm\-moz(1), obm\-nav(1), obm\-xdg(1), openbox(1)
